version: '3.7'

services:
  trac-db:
    build:
      context: PM/trac-db
    image: mikrokosmos/trac-db:${VERSION}
    restart: unless-stopped
    networks:
      - pm
    expose:
      - 5432
  trac-myproject:
    build:
      context: PM/trac-myproject
    image: mikrokosmos/trac-myproject:${VERSION}
    restart: unless-stopped
    depends_on:
      - trac-db
    volumes:
      - trac_data:/var/trac
    networks:
      - pm
    expose:
      - 8000
  redmine-db:
    build:
      context: PM/redmine-db
    image: mikrokosmos/redmine-db:${VERSION}
    restart: unless-stopped
    networks:
      - pm
    expose:
      - 5432
  redmine:
    build:
      context: PM/redmine
    image: mikrokosmos/redmine:${VERSION}
    restart: unless-stopped
    depends_on:
      - redmine-db
    networks:
      - pm
    expose:
      - 3000
  #openproject:
  #  build:
  #    context: PM/openproject
  #  image: mikrokosmos/openproject:${VERSION}
  #  restart: unless-stopped
  #  volumes:
  #    - openproject_pgdata:/var/openproject/pgdata
  #    - openproject_static:/var/openproject/assets
  #  networks:
  #    - pm
  #  expose:
  #    - 8080
  # Free for up to 10 users
  #youtrack:
  #  build:
  #    context: PM/youtrack
  #  image: mikrokosmos/youtrack:${VERSION}
  #  restart: unless-stopped
  #  volumes:
  #    - youtrack_data:/opt/youtrack/data
  #    - youtrack_conf:/opt/youtrack/conf
  #    - youtrack_logs:/opt/youtrack/logs
  #    - youtrack_backups:/opt/youtrack/backups
  #  networks:
  #    - pm
  #  expose:
  #    - 8080

volumes:
  trac_data:
    driver: local
  #openproject_pgdata:
  #  driver: local
  #openproject_static:
  #  driver: local
  #youtrack_data:
  #  driver: local
  #youtrack_conf:
  #  driver: local
  #youtrack_logs:
  #  driver: local
  #youtrack_backups:
  #  driver: local

networks:
  pm:
    driver: bridge
    internal: false
    external: false
