version: '3.7'

services:
  rproxy:
    build:
      context: rproxy
    image: mikrokosmos/rproxy:${VERSION}
    restart: unless-stopped
    depends_on:
      - trac-myproject
      - nexus
      - sonarqube
    networks:
      - pm
      - cicd
    ports:
    - "80:80"

networks:
  cicd:
    driver: bridge
    internal: false
    external: false
