version: '3.7'

services:
  rproxy:
    build:
      context: rproxy
    image: mikrokosmos/rproxy:${VERSION}
    restart: unless-stopped
    depends_on:
      - trac-myproject
      - nexus
      - sonarqube
    networks:
      - mikrokosmos-pm
      - mikrokosmos-cicd
    ports:
      - "443:443"

networks:
  mikrokosmos-cicd:
    driver: bridge
    internal: false
    external: false
  mikrokosmos-pm:
    driver: bridge
    internal: false
    external: false
