version: '3.7'

services:
  rproxy:
    build:
      context: local
    image: mikrokosmos/local:${VERSION}
    restart: unless-stopped
    depends_on:
      - nexus
      - sonarqube
    networks:
      - pm
      - cicd
    ports:
      - "80:80"

networks:
  cicd:
    driver: bridge
    internal: false
    external: false
  pm:
    driver: bridge
    internal: false
    external: false
