version: '3.7'

services:
  #james:
  #  image: linagora/james
  #mailhog:
  #  build:
  #    context: mailhog
  #  image: mikrokosmos/mailhog:${VERSION}
  #  restart: unless-stopped
  #  ports:
  #    - "1025:1025"
  #    - "8025:8025"
  #  #healthcheck:
  #  #  test: echo | telnet 127.0.0.1 1025

networks:
  mikrokosmos-cicd:
    driver: bridge
    internal: false
    external: false
