:author: Ralf Bensmann <ralf@art-of-coding.eu>
:revnumber: DRAFT
:toc: top
:toclevels: 3

== Mikrokosmos

This project provides your own Docker-based development and deployment environment.

* Docker *Library*
** Alpine "latest-stable" base image
** OpenSSH base image
** PostgreSQL
** Redis along with backup solution
** Jekyll
** asciidoc server
* *P* roject *M* anagement
** trac
** Redmine
** (YouTrack)
** (OpenProject)
* *C* ontinuous *I* ntegration / *C* ontinuous *D* eployment
** GitLab Community Edition
** Sonatype Nexus Repository Manager
** SonarQube
* Docker Java Project Template
** Application
** HTTP/TLS Endpoint

.Requirements
* Docker >=19.03.5 installed

=== Setup Mikrokosmos

[source,bash]
----
curl https://raw.githubusercontent.com/artofcoding/mikrokosmos-docker/master/bin/setup-archlinux.sh | bash
----

The script automatically checks out a release and builds Mikrokosmos project management an CI/CD environment:

[source,bash]
----
git clone \
    --depth 1 \
    --branch v1.0 \
    https://github.com/artofcoding/mikrokosmos-docker.git
cd mikrokosmos-docker
./deploy.sh build
----

.Docker Images
[source,text]
----
REPOSITORY                        TAG  IMAGE ID   CREATED     SIZE
mikrokosmos/nexus3                1.0  e3f8dd42e  1 hour ago  635MB
mikrokosmos/sonarqube             1.0  68b8dc59e  1 hour ago  483MB
mikrokosmos/sonarqube-db          1.0  b6034d718  1 hour ago  146MB
mikrokosmos/gitlab-ce             1.0  d724b3c62  1 hour ago  1.88GB
mikrokosmos/trac-myproject        1.0  c8360192a  1 hour ago  312MB
mikrokosmos/rproxy                1.0  6ac7f8d9f  1 hour ago  23.1MB
mikrokosmos/redmine               1.0  4c77c7787  1 hour ago  505MB
mikrokosmos/redmine-db            1.0  8c8c2a02d  1 hour ago  146MB
mikrokosmos/trac-db               1.0  5fa7da7fd  1 hour ago  146MB
mikrokosmos/trac                  1.0  4dfb6687d  1 hour ago  312MB
mikrokosmos/postgres              1.0  e680524bd  1 hour ago  146MB
mikrokosmos/alpine-latest-stable  1.0  ceef70871  1 hour ago  11.7MB
----

.Initialize Mikrokosmos
[source,bash]
----
cd mikrokosmos-docker
./deploy.sh init
----

.deploy.sh ps
[source,text]
----
            Name                   Command          State   Ports
----------------------------------------------------------------------------------
mikrokosmos_nexus_1           sh -c ${SONATYP ...   Up      0.0.0.0:8081->8081/tcp
mikrokosmos_redmine-db_1      /usr/local/bin/ ...   Up      5432/tcp
mikrokosmos_redmine_1         /docker-entrypo ...   Up      3000/tcp
mikrokosmos_rproxy_1          nginx                 Up      0.0.0.0:80->80/tcp
mikrokosmos_sonarqube-db_1    docker-entrypoi ...   Up      5432/tcp
mikrokosmos_sonarqube_1       ./bin/run.sh          Up      0.0.0.0:9000->9000/tcp
mikrokosmos_trac-db_1         docker-entrypoi ...   Up      5432/tcp
mikrokosmos_trac-myproject_1  /trac.sh              Up      8000/tcp
----

==== Local Usage

.Requirements
* 4 GB RAM for Docker

.Networking
Add one or more of the following entries to your local host name file, depending on the services you want to use:

[cols="a,a",options="header"]
|====
| Service
| hosts

| trac
| trac.local

| Redmine
| redmine.local

| (YouTrack)
| youtrack.local

| (GitLab)
| gitlab.local

| Sonatype Nexus
| repo.local

| SonarQube
| sonarqube.local
|====

Some examples:

.UNI*X /etc/hosts
[source,text]
----
127.0.0.1  localhost  trac.local  repo.local  sonarqube.local
----

.macOS /etc/hosts
On macOS please add local hostname too.
[source,text]
----
127.0.0.1  localhost  <local hostname>  trac.local  redmine.local  repo.local  sonarqube.local
----

.Windows C:\Windows\system32\drivers\etc\hosts
[source,text]
----
127.0.0.1  localhost  trac.local  repo.local  sonarqube.local
----

=== Using Mikrokosmos

Nexus
"Enable anonymous access"

==== IntelliJ

.Task Management
[cols="a,a,a",options="header"]
|====
| System
| URL
| Notes

| trac
| http://trac.local/login/xmlrpc
| Search: `search!=closed`

| Redmine
| http://redmine.local
| Activate REST API under Aministration -> Configuration -> API
|====

==== Maven

.Authentication (settings.xml)
[source,xml,linenum]
----
<settings>
    <servers>
        <server>
            <id>nexus-snapshots</id>
            <username>deploy</username>
            <password>deploy</password>
        </server>
        <server>
            <id>nexus-releases</id>
            <username>deploy</username>
            <password>deploy</password>
        </server>
    </servers>
</settings>
----

.Maven Central Mirror (settings.xml)
[source,xml,linenum]
----
<settings>
    <mirrors>
        <mirror>
            <id>mirror-central</id>
            <name>mirror-central</name>
            <url>http://repo.local/nexus/repository/maven-public/</url>
            <mirrorOf>central</mirrorOf>
        </mirror>
    </mirrors>
</settings>
----

.Distribution (pom.xml)
[source,xml,linenum]
----
<project>
    <distributionManagement>
        <snapshotRepository>
            <id>nexus-snapshots</id>
            <url>http://localhost:8999/nexus/repository/maven-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>nexus-releases</id>
            <url>http://localhost:8999/nexus/repository/maven-releases/</url>
        </repository>
    </distributionManagement>
</project>
----

=== Repository Sonatype Nexus3

.Users & Roles
* Role `nx-deploy`
** Rights: `nx-repository-view-*-*-*`
* User `deploy`
** Roles: nx-deploy

==== Docker

.Blob Stores
* docker

.Realms
* Docker Bearer Token Realm

.General Docker repository settings
* "Allow anonymous docker pull (Docker Bearer Token Realm required)"
* "Enable Docker V1 API"

.Pull through Docker Group
[source,bash]
----
docker pull localhost:8997/httpd:2.4-alpine
----

.Push to private Docker repository
[source,bash]
----
docker tag your-own-image:1 localhost:8998/your-own-image:1
docker push localhost:8998/your-own-image:1
----

==== Maven

.Blob Stores
* maven

.Repositories
[cols="a,a,a,a",options="header"]
|====
| Name
| Local URL
| Type
| Settings

4+| Group "Maven Public" +
Access through http://repo.local/maven-public/

| Local Maven Releases
| http://repo.local/maven-releases/
| hosted
|

| Local Maven Snapshots
| http://repo.local/maven-snapshots/
| hosted
|

| Maven Central
| http://repo.local/maven-central/
| proxy
| https://repo1.maven.org/maven2/

| JCenter Bintray
| http://repo.local/maven-bintray/
| proxy
| https://jcenter.bintray.com

| Sonatype Snapshots
| http://repo.local/maven.sonatype-snapshots/
| proxy
| https://oss.sonatype.org/content/repositories/snapshots/

4+| Group "Docker" +
Access through http://repo.local/docker/

| Docker Group
| http://repo.local/docker/
| hosted
| Port 8997

| Docker Private Registry
| http://repo.local/docker-private/
| hosted
| Port 8998

| Docker Hub
| http://repo.local/docker-hub/
| proxy
| https://registry-1.docker.io/ +
"Use Docker Hub"

| Red Hat Docker Registry
| http://repo.local/docker-redhat/
| proxy
| https://registry.access.redhat.com

|====

==== Resources

* https://blog.sonatype.com/using-nexus-3-as-your-repository-part-1-maven-artifacts[Using Nexus3 as Your Repository - Part 1 Maven Artifacts]
* https://blog.sonatype.com/using-nexus-3-as-your-repository-part-3-docker-images[Using Nexus3 as Your Repository - Part 3 Docker Images]
