version: '3.7'

services:
  redmine-db:
    image: postgres:12.1-alpine
    restart: "no"
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=redmine
      - POSTGRES_DB=redmine
    networks:
      - pm
    expose:
      - 5432
  redmine:
    image: redmine:4.1
    restart: "no"
    depends_on:
      - redmine-db
    environment:
      - REDMINE_DB_POSTGRES=redmine-db
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
    networks:
      - pm
    ports:
      - "3000:3000"
  openproject:
    image: openproject/community:10.3
    restart: "no"
    environment:
      - SECRET_KEY_BASE=secret
      #- EMAIL_DELIVERY_METHOD=smtp
      #- SMTP_ADDRESS=smtp.sendgrid.net
      #- SMTP_PORT=587
      #- SMTP_DOMAIN=my.domain.com
      #- SMTP_AUTHENTICATION=login
      #- SMTP_ENABLE_STARTTLS_AUTO=true
      #- SMTP_USER_NAME=apikey
      #- SMTP_PASSWORD=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
    volumes:
      - openproject_pgdata:/var/openproject/pgdata
      - openproject_static:/var/openproject/assets
    networks:
      - pm
    ports:
      - "8080:8080"

volumes:
  openproject_pgdata:
    driver: local
  openproject_static:
    driver: local

networks:
  pm:
    driver: bridge
    internal: false
    external: false
